version: '3'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "9798:80"
#    ssh:
#        build:
#            context: ./ssh
#            dockerfile: Dockerfile
#        ports:
#            - "8823:22"